from typing import List, Optional
from enum import Enum
from pydantic import BaseModel, Field


class MessageDelimiterEnum(str, Enum):
    PERIOD = "."


class AuthorizationRequestMessageFields(BaseModel):
    ProtocolDependentHeader: str = Field(..., max_length=255, description="Protocol uses this header on all transmitted message formats. This field contains one or more protocol characters and precedes the message text. This header typically includes the start-of-text (STX) character.")
    RecordFormat: str = Field(..., min_length=1, max_length=1, description="This one character field identifies this message as a Spark ATM formatted POS message.", enum=["H"])
    ApplicationType: str = Field(..., min_length=1, max_length=1, description="This one character field must contain an ASCII zero.", enum=["0"])
    MessageDelimiter: MessageDelimiterEnum = Field(MessageDelimiterEnum.PERIOD, description="The message delimiter separates the format and application type designators from the body of the message. The message delimiter is defined as a ' ' (Period).")
    BankIDNumber: str = Field(..., max_length=255, description="This fixed length field contains the alphanumeric, host processor assigned. Bank Identification Number (BIN).")
    FieldSeparator: str = Field(..., min_length=3, max_length=3, description="This one character field is used as a separator between various fields in the message.", enum=[":1C"])
    TerminalID: str = Field(..., max_length=8, description="This fixed length field contains the 8 character Terminal ID assigned by the host processor. This field is used to identify a specific terminal. This field must be unique across all terminals within a single host processor.")
    RequestType: str = Field(..., min_length=2, max_length=2, description="This two character field identifies the type of request. An Authorization Request Message contains an 85 in this field.", enum=["85"])
    OperationCode: str = Field(..., min_length=2, max_length=2, description="This two character field defines the operation being requested. The valid values are BI, CW, NW, TR.", enum=["BI", "CW", "NW", "TR"])
    SourceAccount: str = Field(..., min_length=2, max_length=2, description="This two character field defines the source account type for the transaction. The valid values are CA, CR, SA.", enum=["CA", "CR", "SA"])
    DestinationAccount: str = Field(..., min_length=2, max_length=2, description="This two character field defines the destination account type for the transaction. This field is valid for an Operation Code of TR and is ignored otherwise. The valid values are CA, CR, SA.", enum=["CA", "CR", "SA"])
    TransactionSequenceNumber: str = Field(..., max_length=4, description="This fixed length field contains a four digit code which is generated by the terminal as the sequence number for the transaction. The sequence number used by the terminal to match request and response messages. This field is returned by the host processor in an Authorization Response Message. The sequence number is incremented with wrap from 9999 to 0001.")
    Track1Data: str = Field(..., max_length=255, description="This variable length data field contains up to 79 characters of data from track 1 of the magnetic stripe on the consumer's account card. This field includes the data from the start sentinel to the end sentinel inclusive. This field may be empty.")
    Track2Data: str = Field(..., max_length=255, description="This variable length data field contains up to 40 characters of data from track 2 of the magnetic stripe on the consumer's account card. This field from track - includes the data from the start sentinel to the end sentinel inclusive.")
    Track3Data: str = Field(..., max_length=255, description="This is a variable length field that contains up to 106 characters of data from track 3 of the magnetic stripe. This field includes the data from the start sentinel to the end sentinel inclusive. This field may be empty.")
    PINBuffer: str = Field(..., max_length=16, description="This fixed length field will contain the 16 character.")
    TransactionAmount: str = Field(..., max_length=255, description="This variable length field identifies the US dollar and US cents amounts entered at the keyboard. The data is in the following format: ddddddcc Where dddddd represents the whole US dollar amount and cc represents US cents. The US cents field will always be present even if zero.")
    SurchargeAmount: str = Field(..., max_length=255, description="This variable length field identifies the US dollar and US cents surcharge amount programmed locally within the terminal. The data is in the following format: ddcc Where dd represents the whole US dollar amount and cc represents US cents. The US cents field will always be present even if zero.")
    SurchargeEnableFlag: str = Field(..., min_length=1, max_length=1, description="This field indicates whether or not the consumer was presented the surcharge screen and OKed the surcharge amount. The valid values are as follows: - 0: Surcharge screen was not presented to the consumer - 1: Surcharge screen was presented to the consumer", enum=["0", "1"])
    ICCData: str = Field(..., max_length=255, description="This field indicates the set of ICC related data. Refer to Section 5 for detailed elements")
    ProtocolDependentTrailer: str = Field(..., max_length=255, description="The variable-length Protocol Dependent Trailer field indicates the end of the message.")


class AuthorizationResponseMessageFields(BaseModel):
    ProtocolDependentHeader: str = Field(..., max_length=255)
    RecordFormat: str = Field(..., min_length=1, max_length=1, enum=["H"])
    ApplicationType: str = Field(..., min_length=1, max_length=1, enum=["0"])
    MessageDelimiter: MessageDelimiterEnum = Field(MessageDelimiterEnum.PERIOD)
    BankIDNumber: str = Field(..., max_length=255)
    FieldSeparator: str = Field(..., min_length=3, max_length=3, enum=[":1C"])
    TerminalID: str = Field(..., max_length=8)
    ResponseType: str = Field(..., min_length=2, max_length=2, enum=["85"])
    TransactionSequenceNumber: str = Field(..., max_length=4)
    ResponseCode: str = Field(..., min_length=2, max_length=2, enum=["00", "85", "12", "13", "14", "20", "24", "39", "51", "52", "53", "54", "55", "57", "58", "61", "75", "78", "80", "83", "86", "91", "92"])
    LocalTransactionDate: str = Field(..., max_length=6)
    LocalTransactionTime: str = Field(..., max_length=6)
    RetrievalReferenceNumber: str = Field(..., max_length=12)
    SystemTraceAuditNumber: str = Field(..., max_length=6)
    NetworkIDCode: str = Field(..., min_length=2, max_length=2)
    SettlementDate: str = Field(..., max_length=4)
    AccountBalance: str = Field(..., max_length=255)
    AvailableBalance: str = Field(..., max_length=255)
    SurchargeAmount: str = Field(..., max_length=255)
    AuthorizationResponseText: str = Field(..., max_length=255)
    ConfigurationRequestInitiator: str = Field(..., min_length=2, max_length=2)
    ICCData: str = Field(..., max_length=255)
    ProtocolDependentTrailer: str = Field(..., max_length=255)
