[project]
name = "atmcommunication"
version = "1.1.0"
description = "ATM communication project"
dependencies = [
    "flask",
    "flask_jwt_extended"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
