[project]
name = "clientserverimplementation"
version = "0.1.0"
description = "ATM communication project"
dependencies = [
    "socket"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
