openapi: 3.0.0
info:
  title: Authorization Message Fields Specification
  version: 1.0.0
paths: {}
components:
  schemas:
    AuthorizationRequestMessageFields:
      type: object
      properties:
        ProtocolDependentHeader:
          type: string
          description: >
            Protocol uses this header on all transmitted message formats. This field
            contains one or more protocol characters and precedes the message text.
            This header typically includes the start-of-text (STX) character.
        RecordFormat:
          type: string
          description: >
            This one character field identifies this message as a Spark ATM
            formatted POS message.
          enum:
            - H
        ApplicationType:
          type: string
          description: >
            This one character field must contain an ASCII zero.
          enum:
            - "0"
        MessageDelimiter:
          type: string
          description: >
            The message delimiter separates the format and application type
            designators from the body of the message. The message delimiter is
            defined as a ' ' (Period).
          enum:
            - "."
        BankIDNumber:
          type: string
          description: >
            This fixed length field contains the alphanumeric, host processor
            assigned. Bank Identification Number (BIN).
        FieldSeparator:
          type: string
          description: >
            This one character field is used as a separator between various fields in the message.
          enum:
            - ":1C"
        TerminalID:
          type: string
          description: >
            This fixed length field contains the 8 character Terminal ID assigned by
            the host processor. This field is used to identify a specific terminal.
            This field must be unique across all terminals within a single host
            processor.
        RequestType:
          type: string
          description: >
            This two character field identifies the type of request. An
            Authorization Request Message contains an 85 in this field.
          enum:
            - "85"
        OperationCode:
          type: string
          description: >
            This two character field defines the operation being requested. The
            valid values are BI, CW, NW, TR.
          enum:
            - BI
            - CW
            - NW
            - TR
        SourceAccount:
          type: string
          description: >
            This two character field defines the source account type for the
            transaction. The valid values are CA, CR, SA.
          enum:
            - CA
            - CR
            - SA
        DestinationAccount:
          type: string
          description: >
            This two character field defines the destination account type for the
            transaction. This field is valid for an Operation Code of TR and is
            ignored otherwise. The valid values are CA, CR, SA.
          enum:
            - CA
            - CR
            - SA
        TransactionSequenceNumber:
          type: string
          description: >
            This fixed length field contains a four digit code which is generated by
            the terminal as the sequence number for the transaction. The sequence
            number used by the terminal to match request and response messages. This
            field is returned by the host processor in an Authorization Response
            Message. The sequence number is incremented with wrap from 9999 to 0001.
        Track1Data:
          type: string
          description: >
            This variable length data field contains up to 79 characters of data
            from track 1 of the magnetic stripe on the consumer's account card. This
            field includes the data from the start sentinel to the end sentinel
            inclusive. This field may be empty.
        Track2Data:
          type: string
          description: >
            This variable length data field contains up to 40 characters of data
            from track 2 of the magnetic stripe on the consumer's account card. This
            field from track - includes the data from the start sentinel to the end
            sentinel inclusive.
        Track3Data:
          type: string
          description: >
            This is a variable length field that contains up to 106 characters of
            data from track 3 of the magnetic stripe. This field includes the data
            from the start sentinel to the end sentinel inclusive. This field may be
            empty.
        PINBuffer:
          type: string
          description: >
            This fixed length field will contain the 16 character.
        TransactionAmount:
          type: string
          description: >
            This variable length field identifies the US dollar and US cents
            amounts entered at the keyboard. The data is in the following format:
            ddddddcc Where dddddd represents the whole US dollar amount and cc
            represents US cents. The US cents field will always be present even if
            zero.
        SurchargeAmount:
          type: string
          description: >
            This variable length field identifies the US dollar and US cents surcharge
            amount programmed locally within the terminal. The data is in the following format:
            ddcc Where dd represents the whole US dollar amount and cc represents US cents.
            The US cents field will always be present even if zero.
        SurchargeEnableFlag:
          type: string
          description: >
            This field indicates whether or not the consumer was presented the
            surcharge screen and OKed the surcharge amount. The valid values are as follows:
            - 0: Surcharge screen was not presented to the consumer
            - 1: Surcharge screen was presented to the consumer
        ICCData:
          type: string
          description: >
            This field indicates the set of ICC related data. Refer to Section 5 for
            detailed elements
        ProtocolDependentTrailer:
          type: string
          description: >
            The variable-length Protocol Dependent Trailer field indicates the end of
            the message.
      required:
        - RecordFormat
        - ApplicationType
        - MessageDelimiter
        - BankIDNumber
        - FieldSeparator
        - TerminalID
        - RequestType
        - OperationCode
        - SourceAccount
        - DestinationAccount
        - TransactionSequenceNumber
        - Track1Data
        - Track2Data
        - Track3Data
        - PINBuffer
        - TransactionAmount
        - SurchargeAmount
        - SurchargeEnableFlag
        - ICCData
        - ProtocolDependentTrailer
      additionalProperties: false

    AuthorizationResponseMessageFields:
      type: object
      properties:
        ProtocolDependentHeader:
          type: string
          description: >
            Protocol uses this header on all transmitted message formats. This field
            contains one or more protocol characters and precedes the message text.
            This header typically includes the start-of-text (STX) character.
        RecordFormat:
          type: string
          description: >
            This one character field identifies this message as a Spark ATM
            formatted POS message.
          enum:
            - H
        ApplicationType:
          type: string
          description: >
            This one character field must contain an ASCII zero.
          enum:
            - "0"
        MessageDelimiter:
          type: string
          description: >
            The message delimiter separates the format and application type
            designators from the body of the message. The message delimiter is
            defined as a ' ' (Period).
          enum:
            - "."
        BankIDNumber:
          type: string
          description: >
            This fixed length field contains the alphanumeric, host processor
            assigned. Bank Identification Number (BIN).
        FieldSeparator:
          type: string
          description: >
            This one character field is used as a separator between various fields in the message.
          enum:
            - ":1C"
        TerminalID:
          type: string
          description: >
            This fixed length field contains the 8 character Terminal ID assigned by
            the host processor. This field is used to identify a specific terminal.
            This field must be unique across all terminals within a single host
            processor.
        ResponseType:
          type: string
          description: >
            This two character field identifies the type of response. An
            Authorization Response Message contains an 85 in this field.
          enum:
            - "85"
        TransactionSequenceNumber:
          type: string
          description: >
            This fixed length field contains a four digit code which is generated by
            the terminal as the sequence number for the transaction. The sequence
            number used by the terminal to match request and response messages. This
            field is returned by the host processor in an Authorization Response
            Message. The sequence number is incremented with wrap from 9999 to 0001.
        ResponseCode:
          type: string
          description: >
            This two character field contains a response code indicating the status
            of the authorization. See detailed description for valid values.
          enum: 
            - "00"
            - "85"
            - "12"
            - "13"
            - "14"
            - "20"
            - "24"
            - "39"
            - "51"
            - "52"
            - "53"
            - "54"
            - "55"
            - "57"
            - "58"
            - "61"
            - "75"
            - "78"
            - "80"
            - "83"
            - "86"
            - "91"
            - "92"
        LocalTransactionDate:
          type: string
          description: >
            This fixed length field contains the six digit local transaction date
            (MMDDYYYY), calculated by the authorization center using the time zone differential.
            This will be printed on the receipt.
        LocalTransactionTime:
          type: string
          description: >
            This fixed length field contains the six digit local transaction time
            returned by the authorizing system (HHMMSS). This will be printed on the receipt.
        RetrievalReferenceNumber:
          type: string
          description: >
            This fixed length field contains the twelve character retrieval reference
            number returned by the authorizing system. This is returned in a reversal message.
        SystemTraceAuditNumber:
          type: string
          description: >
            This fixed length field contains the six digit system trace audit number
            assigned by the authorizing system. This will be printed on the receipt.
        NetworkIDCode:
          type: string
          description: >
            This two character fixed length field contains the identification code of
            the network on which the transaction was authorized.
        SettlementDate:
          type: string
          description: >
            This four digit fixed length field contains the transaction settlement date
            returned by the authorization system (MMDDYYYY). This will be printed on the
            receipt.
        AccountBalance:
          type: string
          description: >
            This field identifies the US dollar and US cents account balance. The data
            is in the following format: ddddddcc. Where dddddd represents the whole US
            dollar amount and cc represents US cents.
        AvailableBalance:
          type: string
          description: >
            This field identifies the US dollar and US cents available balance. The data
            is in the following format: ddddddcc. Where dddddd represents the whole US
            dollar amount and cc represents US cents.
        SurchargeAmount:
          type: string
          description: >
            This field identifies the US dollar and US cents surcharge amount. The data
            is in the following format: ddcc. Where dd represents the whole US dollar
            amount and cc represents US cents. If this field is empty then the surcharge
            amount held locally within the terminal will be charged to the consumer. If
            this field has a value of zero then no surcharge will be charged to the
            consumer. If the Surcharge Enable Flag in the authorization request message
            was set to '0', then this field should be set to zero.
        AuthorizationResponseText:
          type: string
          description: >
            This variable length field is printed on the receipt when the transaction
            is not approved. If this field is empty, the terminal will decode the response
            code and print an appropriate message.
        ConfigurationRequestInitiator:
          type: string
          description: >
            This two digit field will cause the terminal to request configuration from
            the host processor. A value of 01 in this field will cause the terminal to send a
            Configuration Request Message to the host processor. An empty field or a value of
            00 will not cause a Configuration Request Message to be sent. Any other value will be
            ignored.
        ICCData:
          type: string
          description: >
            This field indicates the set of ICC related data. Refer to Section 5 for
            detailed elements
        ProtocolDependentTrailer:
          type: string
          description: >
            The variable-length Protocol Dependent Trailer field indicates the end of
            the message.
      required:
        - RecordFormat
        - ApplicationType
        - MessageDelimiter
        - BankIDNumber
        - FieldSeparator
        - TerminalID
        - ResponseType
        - TransactionSequenceNumber
        - ResponseCode
        - LocalTransactionDate
        - LocalTransactionTime
        - RetrievalReferenceNumber
        - SystemTraceAuditNumber
        - NetworkIDCode
        - SettlementDate
        - AccountBalance
        - AvailableBalance
        - SurchargeAmount
        - AuthorizationResponseText
        - ConfigurationRequestInitiator
        - ICCData
        - ProtocolDependentTrailer
      additionalProperties: false
