openapi: 3.0.0
info:
  title: Configuration Message Specification
  version: 1.0.0
paths: {}
components:
  schemas:
    ConfigurationRequestMessageFields:
      type: object
      properties:
        ProtocolDependentHeader:
          type: string
          description: >
            Protocol uses this header on all transmitted message formats. This field
            contains one or more protocol characters and precedes the message text.
            This header typically includes the start-of-text (STX) character.
        RecordFormat:
          type: string
          description: >
            This one character field identifies this message as a Spark ATM formatted
            POS message.
          enum:
            - H
        ApplicationType:
          type: string
          description: >
            This one character field must contain an ASCII zero.
          enum:
            - "0"
        MessageDelimiter:
          type: string
          description: >
            The message delimiter separates the format and application type
            designators from the body of the message. The message delimiter is
            defined as a period.
          enum:
            - "."
        BankIDNumber:
          type: string
          description: >
            This fixed length field contains the alphanumeric host processor assigned.
            Bank Identification Number (BIN).
        FieldSeparator:
          type: string
          description: >
            This one character field is used as a separator between various fields in
            the message.
          enum:
            - ":1C"
        TerminalID:
          type: string
          description: >
            This fixed length field contains the 8 character Terminal ID assigned by
            the host processor. This field is used to identify a specific terminal. This
            field must be unique across all terminals within a single host processor.
        RequestType:
          type: string
          description: >
            This two character field identifies the type of request. A Configuration
            Request Message contains an 88 in this field.
          enum:
            - "88"
        UnknownValueField:
          type: string
          description: >
            Unknown value. Not used.
        ProtocolDependentTrailer:
          type: string
          description: >
            The variable-length Protocol Dependent Trailer field indicates the end of
            the message.
      required:
        - RecordFormat
        - ApplicationType
        - MessageDelimiter
        - BankIDNumber
        - FieldSeparator
        - TerminalID
        - RequestType
        - UnknownValueField
        - ProtocolDependentTrailer
      additionalProperties: false

    ConfigurationResponseMessageFields:
      type: object
      properties:
        ProtocolDependentHeader:
          type: string
          description: >
            Protocol uses this header on all transmitted message formats. This field
            contains one or more protocol characters and precedes the message text.
            This header typically includes the start-of-text (STX) character.
        RecordFormat:
          type: string
          description: >
            This one character field identifies this message as an Spark ATM formatted
            POS message.
          enum:
            - H
        ApplicationType:
          type: string
          description: >
            This one character field must contain an ASCII zero.
          enum:
            - "0"
        MessageDelimiter:
          type: string
          description: >
            The message delimiter separates the format and application type
            designators from the body of the message. The message delimiter is
            defined as a period.
          enum:
            - "."
        BankIDNumber:
          type: string
          description: >
            This fixed length field contains the alphanumeric host processor assigned.
            Bank Identification Number (BIN).
        FieldSeparator:
          type: string
          description: >
            This one character field is used as a separator between various fields in
            the message.
          enum:
            - ":1C"
        TerminalID:
          type: string
          description: >
            This fixed length field contains the 8 character Terminal ID assigned by
            the host processor. This field is used to identify a specific terminal. This
            field must be unique across all terminals within a single host processor.
        ResponseType:
          type: string
          description: >
            This two character field identifies the type of response. A Configuration
            Response Message contains an 88 in this field.
          enum:
            - "88"
        LocalDate:
          type: string
          description: >
            This fixed length field contains the eight digit local date (MMDDYYYY)
            calculated by the authorization center using the time zone differential.
        LocalTime:
          type: string
          description: >
            This fixed length field contains the six digit local transaction time returned
            by the authorizing system (HHMMSS).
        HealthMessageTimerValue:
          type: string
          description: Not Used
        TDESWorkingKeyPart1:
          type: string
          description: >
            This fixed length field contains the first 16 chars of the new 32 character
            working Key encrypted with the terminal's Master key.
        SurchargeAmount:
          type: string
          description: >
            This variable length field contains the current per transaction US dollar and
            US cents surcharge amount within the terminal.
        BINListEnableFlag:
          type: string
          description: Not Used
        TDESWorkingKeyPart2:
          type: string
          description: >
            This fixed length field contains the second 16 chars of the new 32 character
            working Key encrypted with the terminal's Master key.
        TDESWorkingKeyPart1Repeated:
          type: string
          description: >
            This fixed length field contains the first 16 chars of the new 32 character
            working Key encrypted with the terminal's Master key. This is a repeat of
            the first TDES Working Key Part 1 above.
        AIDInformation:
          type: string
          description: >
            This field indicates the action to be performed for the list of AIDs on
            Terminal.
          enum:
            - R
            - A
            - D
        AIDList:
          type: string
          description: >
            Fields from ASI to AID repeated as many as Number of AIDs.
        CAPublicKeyInformation:
          type: string
          description: >
            This field indicates the action to be performed for the list of CA Public Keys
            on Terminal.
          enum:
            - R
            - A
            - D
        CAPublicKeyList:
          type: string
          description: >
            Fields from RID to Check Sum repeated as many as Number of Keys.
        ProtocolDependentTrailer:
          type: string
          description: >
            The variable-length Protocol Dependent Trailer field indicates the end of
            the message.
      required:
        - RecordFormat
        - ApplicationType
        - MessageDelimiter
        - BankIDNumber
        - FieldSeparator
        - TerminalID
        - ResponseType
        - LocalDate
        - LocalTime
        - HealthMessageTimerValue
        - TDESWorkingKeyPart1
        - SurchargeAmount
        - BINListEnableFlag
        - TDESWorkingKeyPart2
        - TDESWorkingKeyPart1Repeated
        - AIDInformation
        - AIDList
        - CAPublicKeyInformation
        - CAPublicKeyList
        - ProtocolDependentTrailer
      additionalProperties: false
