openapi: 3.0.0
info:
  title: Reversal Request and Response Message Fields Specification
  version: 1.0.0
paths: {}
components:
  schemas:
    ReversalRequestMessageFields:
      type: object
      properties:
        ProtocolDependentHeader:
          type: string
          description: >
            Protocol uses this header on all transmitted message formats. This field
            contains one or more protocol characters and precedes the message text.
            This header typically includes the start-of-text (STX) character.
        RecordFormat:
          type: string
          description: >
            This one character field identifies this message as an Spark ATM formatted POS message.
          enum:
            - H
        ApplicationType:
          type: string
          description: >
            This one character field must contain an ASCII zero.
          enum:
            - "0"
        MessageDelimiter:
          type: string
          description: >
            The message delimiter separates the format and application type designators
            from the body of the message. The message delimiter is defined as a period.
          enum:
            - "."
        BankIDNumber:
          type: string
          description: >
            This fixed length field contains the alphanumeric, host processor assigned.
            Bank Identification Number (BIN).
        FieldSeparator:
          type: string
          description: >
            This one character field is used as a separator between various fields in the message.
          enum:
            - ":1C"
        TerminalID:
          type: string
          description: >
            This fixed length field contains the 8 character Terminal ID assigned by
            the host processor. This field is used to identify a specific terminal. This
            field must be unique across all terminals within a single host processor.
        RequestType:
          type: string
          description: >
            This two-character field identifies the type of request. Request Message
            contains an 86 in this field.
          enum:
            - "86"
        LocalTransactionDate:
          type: string
          description: >
            This fixed length field contains the six digit local date (MMDDYYYY),
            calculated by the authorization center using the time zone differential.
          pattern: "[0-9]{8}"
        LocalTransactionTime:
          type: string
          description: >
            This fixed length field contains the six digit local transaction time
            returned by the authorizing system (HHMMSS).
          pattern: "[0-9]{6}"
        RetrievalReferenceNumber:
          type: string
          description: >
            This fixed length field contains the twelve-character retrieval reference
            number returned by the authorizing system.
        RequestedDollarAmount:
          type: string
          description: >
            This field identifies the US dollar and US cents amounts entered at the
            keyboard.
        DispensedDollarAmount:
          type: string
          description: >
            This field identifies the US dollar amount dispensed by the terminal.
        SurchargeAmount:
          type: string
          description: >
            This field identifies the US dollar and US cents surcharge amount held
            locally within the terminal.
        SurchargeEnableFlag:
          type: string
          description: >
            This field indicates whether or not the consumer was presented the surcharge
            screen and OKed the surcharge amount.
          enum:
            - "0"
            - "1"
        ICCData:
          type: string
          description: >
            This field indicates the set of ICC related data.
        ProtocolDependentTrailer:
          type: string
          description: >
            The variable-length Protocol Dependent Trailer field indicates the end of the message.
      required:
        - RecordFormat
        - ApplicationType
        - MessageDelimiter
        - BankIDNumber
        - FieldSeparator
        - TerminalID
        - RequestType
        - LocalTransactionDate
        - LocalTransactionTime
        - RetrievalReferenceNumber
        - RequestedDollarAmount
        - DispensedDollarAmount
        - SurchargeAmount
        - SurchargeEnableFlag
        - ICCData
        - ProtocolDependentTrailer
      additionalProperties: false

    ReversalResponseMessageFields:
      type: object
      properties:
        ProtocolDependentHeader:
          type: string
          description: >
            Protocol uses this header on all transmitted message formats. This field
            contains one or more protocol characters and precedes the message text.
            This header typically includes the start-of-text (STX) character.
        RecordFormat:
          type: string
          description: >
            This one character field identifies this message as a Spark ATM formatted POS message.
          enum:
            - H
        ApplicationType:
          type: string
          description: >
            This one character field must contain an ASCII zero.
          enum:
            - "0"
        MessageDelimiter:
          type: string
          description: >
            The message delimiter separates the format and application type designators
            from the body of the message. The message delimiter is defined as a period.
          enum:
            - "."
        BankIDNumber:
          type: string
          description: >
            This fixed length field contains the alphanumeric, host processor assigned.
            Bank Identification Number (BIN).
        FieldSeparator:
          type: string
          description: >
            This one character field is used as a separator between various fields in the message.
          enum:
            - ":1C"
        TerminalID:
          type: string
          description: >
            This fixed length field contains the 8 character Terminal ID assigned by
            the host processor. This field is used to identify a specific terminal. This
            field must be unique across all terminals within a single host processor.
        ResponseType:
          type: string
          description: >
            This two-character field identifies the type of response. A Reversal Response Message contains an 86 in this field.
          enum:
            - "86"
        ConfigurationRequestInitiator:
          type: string
          description: >
            This two-digit field will cause the terminal to request configuration from
            the host processor.
          pattern: "[0-9]{2}"
        ICCData:
          type: string
          description: >
            This field indicates the set of ICC related data. Refer to Section 5 for detailed elements.
        ProtocolDependentTrailer:
          type: string
          description: >
            The variable-length Protocol Dependent Trailer field indicates the end of the message.
      required:
        - RecordFormat
        - ApplicationType
        - MessageDelimiter
        - BankIDNumber
        - FieldSeparator
        - TerminalID
        - ResponseType
        - ConfigurationRequestInitiator
        - ICCData
        - ProtocolDependentTrailer
      additionalProperties: false
